name: Publish Docker image 

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
          
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and Publish Docker Image
      run: |
        docker build -t ainafahlgren/grupp8uppgift .
        docker push ainafahlgren/grupp8uppgift